format = """
[](#fe8019)\
$shell\
[](bg:#434C5E fg:#fe8019)\
$directory\
[](fg:#434C5E bg:#fb4934)\
$git_branch\
[](fg:#fb4934 bg:#33658A)\
$git_status\
$time\
[ ](fg:#33658A)\
"""
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = false
style_user = "bg:#fe8019"
style_root = "bg:#fe8019"
format = '[$user ]($style)'

[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"stampen" = " "
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#fb4934"
format = '[ $symbol $branch ]($style)'
truncation_length = 20

[git_status]
style = "bg:#33658A"
format = '[ $all_status$ahead_behind]($style)'
disabled = true

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'
disabled = true

[shell]
disabled = false
bash_indicator = " " 
style = "bg:#fe8019"
format = '[$indicator ]($style)'

[aws]
format = '[ $symbol($profile )]($style)'
style = 'bg:#06969A'
symbol = '󰸏 '
disabled = true

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ $time ]($style)'
